spring:
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/guestbook
        username: root
        password:
    # default get & post => enable HttpMethod
    mvc:
        hiddenmethod:
            filter:
                enabled: true

server:
    port: 9090
    # get endpoint
    base:
        url: "http://localhost:8080"